codekamp/src/lostsoul/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('lostsoul_api.urls', namespace='lostsoul_api')),
    path('', include('lostsoul_web.urls', namespace='lostsoul_web')),
]

codekamp/src/lostsoul_web/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'lostsoul_web'

urlpatterns = [
    path('articles', views.list_articles, name='article_list'),
    path('articles/add', views.add_artile, name='add_new_article'),
    path('oauth/facebook', views.facebook_oauth, name='facebook_oauth'),
    path('oauth/github', views.github_oauth, name='github_oauth'),
    path('articles/<str:my_slug>', views.get_article, name='article_detail'),
    path('auth/login', auth_views.LoginView.as_view(), name='login_page')
]

codekamp/src/lostsoul_web/models.py
from django.db import models
from django.utils.text import slugify
from django.dispatch import receiver
from django.contrib.auth.models import User





# class User(AbstractUser):
#     bio = models.TextField()


class Article(models.Model):
    title = models.CharField(max_length=1000)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

# class Profile(models.Model):
#     bio = models.TextField()
#     owner = models.OneToOneField()
#
#
# @receiver(models.signals.post_save, sender=User)
# def createProfile(sender, instance, created, **c):
#     if(created):
#         Profile.objects.create(user=instance)
#
# @receiver(models.signals.post_save, sender=User)
# def saveProfile(sender, instance, **c):
#     instance.profile.save()


@receiver(models.signals.pre_save, sender=Article)
def set_slug(sender, instance, **c):
    if not instance.slug:
        instance.slug = slugify(instance.title)


# https://scotch.io/bar-talk/s-o-l-i-d-the-first-five-principles-of-object-oriented-design

codekamp/src/lostsoul_web/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.crypto import get_random_string
from pip._vendor import requests

from lostsoul_web.models import Article


def list_articles(request):
    state = get_random_string(32)
    user_city = 'Ghaziabad'

    print(request.user.id)
    cache.set(state, request.user.id, 6000)


    requests.post("https://api.twitter.com/oauth/request_token")

    # ip_addr = request.META.get('REMOTE_ADDR')
    # ip_addr = '43.225.0.133'
    #
    # res = requests.get('http://freegeoip.net/json/' + ip_addr).json()
    # user_city = res['city']
    #
    # credentials = {'password': 'rajneesh10', 'email': '101.prashant@gmail.com'}
    # res = requests.get('https://api.invidz.com/api/authenticate', params=credentials).json()
    #
    # token = res['token']
    # print(res['user']['first_name'])
    #
    #
    # token_header = {'Authorization': 'bearer ' + token}
    # videos = requests.get('https://api.invidz.com/api/videos', headers=token_header).json()
    #
    # print(videos['data'][3]['title'])
    query = ''
    try:
        query = request.GET['q']
        articles = Article.objects.filter(title__icontains=query)
    except:
        articles = Article.objects.all()

    return render(request, 'list-articles.html',
                  {'my_articles': articles, 'query': query, 'city': user_city, 'state': state})


def get_article(request, my_slug):
    article = Article.objects.get(slug=my_slug)
    return render(request, 'get-article.html', {'article': article})


@login_required()
def add_artile(request):
    title = ''
    content = ''
    error = False

    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']

        if len(title) > 30:
            error = True
        else:
            author = request.user.detail[0].bio
            article = Article.objects.create(title=title, content=content, author=author)
            return redirect('lostsoul_web:article_detail', article.slug)

    return render(request, 'add-article.html', {'title': title, 'content': content, 'error': error})


def facebook_oauth(request):
    grant = request.GET['code']
    state = request.GET['state']

    user_id = cache.get(state)

    if (user_id == request.user.id):
        client_secret = ''
        data = {'client_id': '', 'redirect_uri': 'http://localhost:8080/oauth/facebook',
                'client_secret': client_secret, 'code': grant}
        res = requests.get(
            'https://graph.facebook.com/v2.12/oauth/access_token', params=data).json()
        request.user.facebook_token = res['access_token']
        request.user.save()

        print(res['access_token'])

        return redirect('lostsoul_web:add_new_article')

def github_oauth(request):
    grant = request.GET['code']
    state = request.GET['state']

    user_id = cache.get(state)

    if (user_id == request.user.id):
        client_id = '99483968851edaa50f7f'
        client_secret = '65737905e37e46bceae4cb8d575971b57db1d0e7'
        data = {'client_id': client_id, 'redirect_uri': 'http://localhost:8080/oauth/github',
                'client_secret': client_secret, 'code': grant}

        headers = {'Accept': 'application/json'}
        res = requests.post(
            'https://github.com/login/oauth/access_token', params=data, headers=headers).json()
        request.user.facebook_token = res['access_token']
        request.user.save()

        emailRes = requests.get('https://api.github.com/user/emails?access_token=' + res['access_token'])
        print(emailRes)
        return redirect('lostsoul_web:add_new_article')

codekamp/src/lostsoul_web/templates/add-article.html
{% extends 'main.html' %}


{% block page_content %}
    {% if error %}
        <span style="color: red">Please fix error and resubmit</span>
    {% endif %}
    <div></div>
    <form method="post" action="{% url 'lostsoul_web:add_new_article' %}">
        {% csrf_token %}
        <input name="title" placeholder="title" value="{{ title }}">
        <textarea name="content" placeholder="write something...">{{ content }}</textarea>
        <button type="submit">Submit</button>
    </form>
{% endblock %}

{% block page_title %}
    <title>Add New Article</title>
{% endblock %}

codekamp/src/lostsoul_web/templates/get-article.html
{% extends 'main.html' %}


{% block page_content %}
        <h1>{{ article.title }}</h1>
        <span>{{ article.author.first_name }}</span>
        <span>{{ article.created_at | date:"Y d" }}</span>

        <div>{{ article.content }}</div>
{% endblock %}

{% block page_title %}
    <title>{{ article.title }}</title>
    <meta property="og:title" content="{{ article.title }}">
{% endblock %}

codekamp/src/lostsoul_web/templates/list-articles.html
{% extends 'main.html' %}


{% block page_content %}
    <p>We are spying on you and we know you are from {{ city }}</p>
    <a href="https://github.com/login/oauth/authorize?client_id=99483968851edaa50f7f&scope=user&redirect_uri=http://localhost:8080/oauth/github&state={{ state }}">Connect Your Github</a>
    <form action="{% url 'lostsoul_web:article_list' %}" method="get">
        <input name="q" placeholder="type keywords.." value="{{ query }}">
        <button type="submit">Search</button>
    </form>
    <a href="{% url 'lostsoul_web:add_new_article' %}">add new article</a>
    <ul>
        {% for aritcle in my_articles %}
            <li><a href="{% url 'lostsoul_web:article_detail' aritcle.slug %}">{{ aritcle.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

{% block page_title %}
    <title>All articles</title>
{% endblock %}

codekamp/src/lostsoul_web/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block page_title %}
        <title>My Main layout</title>
    {% endblock %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Lost Soul</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'lostsoul_web:article_list' %}">Articles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/about-us">About us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'lostsoul_web:login_page' %}">Login</a>
            </li>
        </ul>
    </div>
</nav>

{% block page_content %}
    hello world!
{% endblock %}
</body>
</html>